import javax.swing.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.jpos.iso.ISOMsg;
import org.jpos.iso.ISOUtil;
import org.jpos.iso.channel.NACChannel;
import org.jpos.iso.packager.ISO87BPackager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author Victorino
 */

// rq.set(2, "827629"); // DirecTV
// rq.set(3, "370000");
// rq.set(4, "000000000500");
// rq.set(11,"001780");
// // 2012/02/02
// rq.set(12,"174952");
// rq.set(13,"0619");
// rq.set(22,"012");
// rq.set(24,"026");
// rq.set(25,"00");
// rq.set(38,"856972");
// rq.set(41,"DIF03481");
// rq.set(42,"240259000500004");
// rq.set(112,"1202000242480986 ");
// rq.set(114,"03");
// rq.set(116,"12341234");
//

public class UiEnviar extends JFrame {

    /**
     * Creates new form UiEnviar
     */

    ISOMsg request = null;

    public UiEnviar() {
        super("REGULARIZACIONES DIRECTV RETAIL V100");
        initComponents();
    }

    private ISOMsg obtenerMensajeISO() {
        ISOMsg request = new ISOMsg("0200");

        try {
            request.set(2, "827629");
            request.set(3, "370000");
            // Monto
            if (montoJT.getText().compareTo("") != 0) {
                request.set(4, montoJT.getText());
            } else {
                return null;
            }
            // MID
            if (midJT.getText().compareTo("") != 0) {
                request.set(42, midJT.getText());
            } else {
                return null;
            }
            // TID|
            if (tidJT.getText().compareTo("") != 0) {
                request.set(41, tidJT.getText());
            } else {
                return null;
            }
            // SIM CARD
            if (simCardJt.getText().compareTo("") != 0) {
                String tempo = new String();
                tempo = ISOUtil.padright(simCardJt.getText(), 20, ' ');
                request.set(112, "1202" + tempo);
            } else {
                return null;
            }
            // referencia
            if (referenciaJT.getText().compareTo("") != 0) {
                String tempo = new String();
                tempo = ISOUtil.padright(referenciaJT.getText(), 6, '0');
                request.set(11, tempo);
            } else {
                return null;
            }
            // autorizacion
            if (autorizacionJT.getText().compareTo("") != 0) {
                String tempo = new String();
                tempo = ISOUtil.padright(autorizacionJT.getText(), 6, '0');
                request.set(38, tempo);
            }
            // Cajero y Clave
            if (cajeroJT.getText().compareTo("") != 0 && claveJT.getText().compareTo("") != 0) {
                String tempo = new String();
                tempo = cajeroJT.getText() + claveJT.getText();
                request.set(116, tempo);
            } else {
                return null;
            }

            // Fecha
            if (fechaJT.getText().compareTo("") != 0) {

                request.set(13, fechaJT.getText());
            } else {
                return null;
            }
            // Hora
            if (horaJT.getText().compareTo("") != 0) {

                request.set(12, horaJT.getText());
            } else {
                return null;
            }

            request.set(24, "026");
            request.set(25, "00");
            request.set(22, "012");

        } catch (Exception ex) {
            Logger.getLogger(UiEnviar.class.getName()).log(Level.SEVERE, null, ex);
        }

        return request;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visorJTA = new javax.swing.JTextArea();
        enviarJB = new javax.swing.JButton();
        salirJB = new javax.swing.JButton();
        tidJT = new javax.swing.JTextField();
        midJT = new javax.swing.JTextField();
        simCardJt = new javax.swing.JTextField();
        referenciaJT = new javax.swing.JTextField();
        autorizacionJT = new javax.swing.JTextField();
        cajeroJT = new javax.swing.JTextField();
        claveJT = new javax.swing.JTextField();
        fechaJT = new javax.swing.JTextField();
        horaJT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        montoJT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ipJT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        puertoJT = new javax.swing.JTextField();
        Borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("COMERCIO ID");

        jLabel2.setText("TERMINAL ID");

        jLabel3.setText("SIM CARD");

        jLabel4.setText("REFERENCIA");

        jLabel5.setText("AUTORIZACION");

        jLabel6.setText("CAJERO");

        jLabel7.setText("CLAVE");

        jLabel8.setText("FECHA");

        jLabel9.setText("HORA");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("REGULARIZAR TRANSACCIONES DIRECTV RETAIL");

        visorJTA.setColumns(20);
        visorJTA.setRows(5);
        jScrollPane1.setViewportView(visorJTA);

        enviarJB.setText("Enviar");
        enviarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarJBActionPerformed(evt);
            }
        });

        salirJB.setText("Salir");

        jLabel11.setText("MONTO");

        jLabel12.setText("IP / HOST");

        ipJT.setText("192.168.3.32");

        jLabel13.setText("PUERTO");

        puertoJT.setText("9001");

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4).addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup().addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11).addComponent(jLabel9)))
                                .addComponent(jLabel1).addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8).addComponent(jLabel7)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addComponent(jLabel10).addContainerGap(130,
                                Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup().addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(midJT, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tidJT, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(simCardJt, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(referenciaJT, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(autorizacionJT, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cajeroJT, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(claveJT, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fechaJT, javax.swing.GroupLayout.Alignment.TRAILING).addComponent(horaJT)
                                .addComponent(montoJT, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup().addGap(55, 55, 55)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel12).addComponent(jLabel13))
                                                .addGap(48, 48, 48)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ipJT, javax.swing.GroupLayout.PREFERRED_SIZE, 129,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(puertoJT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(25, 25, 25)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(enviarJB, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(salirJB, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup().addGap(18, 18, 18).addComponent(
                                                jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(Borrar,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addGap(23, 23, 23).addComponent(jLabel10).addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup().addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
                                .addComponent(midJT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(ipJT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2).addComponent(tidJT,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel13).addComponent(puertoJT,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3).addComponent(simCardJt,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(referenciaJT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(autorizacionJT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6).addComponent(cajeroJT,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(claveJT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(fechaJT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9).addComponent(horaJT,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11).addComponent(montoJT,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup().addComponent(enviarJB).addGap(18, 18, 18)
                                .addComponent(salirJB).addGap(18, 18, 18).addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Borrar).addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarJBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_enviarJBActionPerformed
        // TODO add your handling code here:
        ISOMsg requestMsg = null;
        ISOMsg responseMsg = null;
        NACChannel channel = null;
        String ip = null;
        int puerto = 0;
        byte[] tpdu = {0x60, 0x50, 0x00, 0x00, 0x01};

        requestMsg = obtenerMensajeISO();

        ip = ipJT.getText();

        puerto = Integer.parseInt(puertoJT.getText());

        if (requestMsg != null) {

            // channel = new NACChannel ("192.168.3.31", 7001, new ISO87BPackager(),
            // tpdu,NACChannel.PACKAGER1);
            channel = new NACChannel(ip, puerto, new ISO87BPackager(), tpdu);
            try {
                DataOutputStream dos = null;
                BufferedWriter d;

                channel.setTimeout(15000);
                channel.connect();
                visorJTA.append("CONECTADO A " + ip + ": " + puerto + "\n");
                channel.send(requestMsg);
                visorJTA.append("ENVIANDA PAQUETE ISO8583" + "\n");

                visualizarTramaISO8583(requestMsg, 0);

                responseMsg = channel.receive();
                if (responseMsg != null) {
                    // visorJTA.append(responseMsg.dump(null, ip));
                    visualizarTramaISO8583(responseMsg, 1);

                } else {
                    visorJTA.append("NO HAY RESPUESTA" + "\n");
                }

            } catch (Exception ex) {
                Logger.getLogger(UiEnviar.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }// GEN-LAST:event_enviarJBActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BorrarActionPerformed
        // TODO add your handling code here:
        visorJTA.setText("");
    }// GEN-LAST:event_BorrarActionPerformed

    public void visualizarTramaISO8583(ISOMsg msg, int flag) {
        int campos = 1;

        if (msg != null) {
            if (flag == 0) {
                visorJTA.append("MSG ISO8583 OUTPUT" + "\n");
            } else {
                visorJTA.append("MSG ISO8583 INPUT" + "\n");
            }

            for (campos = 0; campos <= 128; campos++) {
                if (msg.hasField(campos)) {
                    visorJTA.append("Campo = " + campos + "  Valor = " + msg.getString(campos) + "\n");
                }
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UiEnviar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UiEnviar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UiEnviar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UiEnviar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UiEnviar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton Borrar;
    private JTextField autorizacionJT;
    private JTextField cajeroJT;
    private JTextField claveJT;
    private JButton enviarJB;
    private JTextField fechaJT;
    private JTextField horaJT;
    private JTextField ipJT;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JScrollPane jScrollPane1;
    private JTextField midJT;
    private JTextField montoJT;
    private JTextField puertoJT;
    private JTextField referenciaJT;
    private JButton salirJB;
    private JTextField simCardJt;
    private JTextField tidJT;
    private JTextArea visorJTA;
    // End of variables declaration//GEN-END:variables
}
